NOT_UNDERSTAND = 'Ich verstehe deine Eingabe nicht.\n'
NOT_ALIVE = 'Die Person lebt leider nicht mehr...\n'
INPUT_ONE = 'Benutze dafür bitte den __globalen oder Servernamen der Person (*ohne* `@`).__'
INPUT_MORE = 'Benutze dafür bitte den __globalen oder Servernamen der Personen (*ohne* `@`)__ und trenne mit einem *Komma*.'

THIEF_ROLE = 'Dieb'
THIEF_PHASE = 'THIEF'
THIEF_FINISHED = 'Der **Dieb** hat eine Identität gestohlen und geht zufrieden schlafen.'

CUPID_ROLE = 'Amor'
CUPID_PHASE = 'CUPID'
CUPID_WAKE = '**Amor** wacht auf. Er hat auf einmal große Lust, zwei Leute mit seinen Liebespfeilen abzuschießen, um ein bisschen mehr Spannung in seinem Leben zu haben.'
CUPID_INPUT = 'Wen möchtest du mit deinen Liebespfeilen abschießen? ' + INPUT_MORE
CUPID_FINISHED = '**Amor** hat sich zwei Personen ausgesucht, die sich ineinander verlieben sollen und geht in Ruhe schlafen.'

WILD_CHILD_ROLE = 'Wildes Kind'
WILD_CHILD_PHASE = 'WILD CHILD'
WILD_CHILD_WAKE = 'Das **wilde Kind** wacht auf. Es sucht sich ein Vorbild. Wenn dieses stirbt, kehrt das wilde Kind zurück zu den Werwölfen und wird deren Verbündeter.'
WILD_CHILD_INPUT = 'Wer soll dein Vorbild sein? ' + INPUT_ONE
WILD_CHILD_FINISHED = 'Das **wilde Kind** hat sich ein Vorbild ausgesucht und geht wieder schlafen.'
WILD_CHILD_RM_DIED = 'Dein Vorbild ist gestorben. Du agierst jetzt als Werwolf.'

HEALER_ROLE = 'Heiler'
HEALER_PHASE = 'HEALER'
HEALER_WAKE = 'Der **Heiler** erwacht. Er hat ein ganz ungutes Gefühl und möchte deshalb diese Nacht jemanden beschützen.'
HEALER_INPUT = 'Welche Person möchtest du beschützen? (Du kannst auch dich selbst schützen.) '
HEALER_SAME_IN_ROW = 'Du kannst nicht zwei Mal hintereinander dieselbe Person schützen. Wähle bitte jemand anderes.'
HEALER_FINISHED = 'Der **Heiler** hat eine Person gefunden, die es würdig ist, beschützt zu werden und geht wieder schlafen.'

SEER_ROLE = 'Seherin'
SEER_PHASE = 'SEER'
SEER_WAKE = 'Die **Seherin** wacht auf. Sie verdächtigt jemanden und möchte deshalb die Identität dieser Person in Erfahrung bringen.'
SEER_INPUT = 'Wen möchtest du überprüfen? ' + INPUT_ONE
SEER_FINISHED = 'Die **Seherin** hat etwas Interessantes gesehen und geht wieder schlafen.'

WEREWOLF_ROLE = 'Werwolf'
WEREWOLVES_PHASE = 'WEREWOLVES'
WEREWOLVES_PHASE_CONFIRM = 'WEREWOLVES_CONFIRMING'
WEREWOLVES_WAKE = 'Die **Werwölfe** wachen auf und haben richtig Hunger. Sie müssen sich nur noch einigen, wen sie diese Nacht fressen wollen.'
WEREWOLVES_INPUT = ', wer soll gefressen werden? ' + INPUT_ONE + 'Wenn jemand nicht wählen will oder kann, kann er auch `Enthaltung` eingeben.\nIhr könnt euch auch vorher absprechen.'
WEREWOLVES_LOVE = 'Du kannst deinen Liebespartner doch nicht fressen! 💔'
WEREWOLVES_WHO_TO_KILL = 'Ich weiß jetzt nicht genau, wen ihr umbringen wollt, könnt ihr nochmal stimmen?'
WEREWOLVES_FINISHED = 'Die **Werwölfe** haben ihr Opfer gefunden und gehen wieder schlafen.'

WHITE_WEREWOLF_ROLE = 'Weißer Werwolf'
WHITE_WEREWOLF_PHASE = 'WHITE_WEREWOLF'
WHITE_WEREWOLF_WAKE = 'Der **weiße Werwolf** erwacht. Er möchte eventuell einen seiner Werwolf-Kameraden fressen.'
WHITE_WEREWOLF_INPUT = 'Wen möchtest du fressen? ' + INPUT_ONE + ' (Wenn du niemanden fressen möchtest, antworte mit `Niemanden`)'
WHITE_WEREWOLF_LOVE = 'Du kannst deinen Liebespartner doch nicht fressen! 💔'
WHITE_WEREWOLF_FINISHED = 'Der **weiße Werwolf** hat einen seiner Kameraden gefressen (oder auch nicht) und geht wieder schlafen.'

WITCH_ROLE = 'Hexe'
WITCH_PHASE_HEAL = 'WITCH_HEAL'
WITCH_PHASE_KILL = 'WITCH_KILL'
WITCH_WAKE = 'Die **Hexe** wacht durch die Geräusche auf, die die Werwölfe verursacht haben. Sie sieht sich im Dorf um.'
WITCH_ALREADY_HEALED = 'Deinen Heiltrank hast du bereits genutzt.'
WITCH_INPUT_HEAL = ' ist gestorben. Möchtest du diese Person mit deinem Heiltrank retten?'
WITCH_ALREADY_KILLED = 'Deinen Gifttrank hast du schon genutzt. Also gehst du wieder schlafen.'
WITCH_NO_TRANKS = 'Du hast keine Tränke mehr, die du nutzen kannst. (Wir warten jetzt pseudomäßig trotzdem. 😈)'
WITCH_INPUT_KILL = 'Möchtest du noch jemanden mit deinem Gifttrank vergiften? ' + INPUT_ONE + ' (Wenn du niemanden töten willst, antworte einfach mit `Nein`)'
WITCH_LOVE = 'Du kannst deinen Liebespartner doch nicht vergiften! 💔'
WITCH_NO_KILLING = 'Du willst niemanden vergiften und gehst wieder schlafen.'
WITCH_FINISHED = 'Die **Hexe** hat eventuell einen oder beide ihrer Tränke verwendet und geht wieder schlafen.'

MORNING = 'Die Sonne geht auf und der Tag bricht an. Alle wachen auf.'
NO_ONE_DIED = 'Niemand ist gestorben! 🎉'
CITIZENS_SLEEP = 'Nach diesem anstrengenden Tag gehen alle wieder schlafen.'

VOTING_PHASE = 'VOTING'

JUDGE_ROLE = 'Stotternder Richter'
JUDGE_NEW_VOTE_POSSIBLE = 'Bis zum Ende der ersten Abstimmung kannst du mir mit der Nachricht `ABSTIMMUNG` sagen, dass du noch eine zweite Abstimmung direkt nach der ersten Abstimmung möchtest'
JUDGE_NO_VOTE_POSSIBLE = 'Die Abstimmung ist beendet und du kannst diese Runde keine zweite Abstimmung herbeiführen.'
JUDGE_NEW_VOTE = 'Der stotternde Richter hat eine neue Abstimmungsrunde angeordnet! Ihr müsst also sofort erneut jemanden wählen, den ihr hinrichten wollt. (Wenn sich jemand entschieden hat, die gewünschte Person bitte mit einem `@` taggen.)'

ANGRY_MOB = 'In eurer Stadt passieren seltsame Dinge und ihr seid alle ein wütender Mob mit Fackeln 🔥 und Mistgabeln 🍴. Ihr wollt jemanden wählen, den ihr verbrennen (oder aufspießen) könnt. (Wenn sich jemand entschieden hat, die gewünschte Person bitte mit einem `@` taggen.)\nACHTUNG: Es gibt nur eine Wahlrunde, also entscheidet weise (und denkt ggf. an Dorfdepp und Sündenbock)!'
CITIZEN_LOVE = 'Du kannst doch nicht gegen deinen Liebespartner stimmen! 💔'
SCAPEGOAT_ROLE = 'Sündenbock'
VOTE_DRAW = 'Ihr konntet euch nicht einig werden und da es keinen Sündenbock gibt, stirbt heute niemand mehr.'
IDIOT_ROLE = 'Dorfdepp'
VOTE_IDIOT = 'Ihr habt den Dorfdeppen erwischt! Er stirbt nicht, verliert aber ab jetzt sein Stimmrecht.'

HUNTER_ROLE = 'Jäger'
HUNTER_PHASE_NIGHT = 'HUNTER_NIGHT'
HUNTER_PHASE_VOTE = 'HUNTER_VOTE'
HUNTER_DIED = 'Der Jäger ist gestorben. '
HUNTER_INPUT = ', wen möchtest du als letzte Tat noch mit dir in den Tod reißen? Tagge die gewünschte Person bitte mit einem `@`'

OLD_MAN_ROLE = 'Alter Mann'
OLD_MAN_DIED = ' den **alten Mann** getötet! Aus Verzweiflung, einen solch hochgelehrten Mann verloren zu getötet zu haben, verlieren alle Dorfbewohner ihre besonderen Fähigkeiten. *Alle sind nun gewöhnliche Dorfbewohner*.'

GAME_OVER = '*Das Spiel ist beendet!* '
BAD_WON = 'Die **Werwölfe** haben gewonnen! '
GOOD_WON = 'Die **Dorfbewohner** haben gewonnen! '
COUPLE_WON = 'Das **Liebespaar** hat gewonnen! '
WHITE_WEREWOLF_WON = 'Der **weiße Werwolf** hat gewonnen! '
NOONE_WON = '___Alle___ sind gestorben. Es gibt keinen Gewinner, nur Verlierer. :('